### ISSUE TITLE
ERROR during import of DJI flight logs

### ISSUE THREAD

**Issue by buhln** [remisalmon/strava-local-heatmap#15]
First: Great tool and thank you for your effort!

By importing GPX-tracks from my DJI drone I get in some trouble.

```
RuntimeWarning: invalid value encountered in true_divide
  data = (data-data.min())/(data.max()-data.min()) # normalize to [0,1]
```

The heatmap is saved but without any tracks. I pinpointed the error to line 239f. It looks like the data array is not correctly assigned.
```
    for i, j in ij_data:
        data[i-sigma_pixel:i+sigma_pixel, j-sigma_pixel:j+sigma_pixel] += 1.0
```
At the end the data array contains only zeros. 

I uploaded the gpx track here for debugging (just rename it to *.gpx):
[DJIFlightRecord_2022-02-09_16-07-50.txt](https://github.com/remisalmon/Strava-local-heatmap/files/8053434/DJIFlightRecord_2022-02-09_16-07-50.txt)

I am ready to support, but at the moment I am not able to find the problem. ;-)
Thanks in advance.
nico

**Comment by remisalmon** [comment]
Should be fixed with that last commit, feel free to re-open if you still see this issue.
