### ISSUE TITLE
Black background / no tiles

### ISSUE THREAD

**Issue by rapliandras** [remisalmon/strava-local-heatmap#20]
Wikimedia tile server is offline. I tried experimenting with others such as openstreetmap, for example like this:

`OSM_TILE_SERVER = 'https://tile.openstreetmap.org/{}/{}/{}.png'
`

I can download these tiles manually, but for some reason, the generated output is still a big black background. There's no warnings or errors during run.

**Comment by Natenom** [comment]
You need to also change the user agent in line 92 to anything, like strava-heatmap for example.

Then it works. At least for me. :)

Using the user agent in the script you get a 403 (Forbidden) via wget, it only works in your browser.

See https://operations.osmfoundation.org/policies/tiles/ "Technical Usage Requirements".

**Comment by gzakhour** [comment]
I also encounter the same error.

When I run `python3 strava_local_heatmaps.py` I get for the following error while downloading more than half of the tiles (the `%d` are placeholders).

```
ERROR downloading tile https://maps.wikimedia.org/osm-intl/%d/%d/%d.png failed, using blank tile
```

To generate the complete heatmap correctly I changed the `OSM_TILE_SERVER` constant to `https://tile.openstreetmap.org/{}/{}/{}.png` (just as @rapliandras  did) and to abide by [OSM's usage policy](https://operations.osmfoundation.org/policies/tiles/) I used the user-agent: `Strava-local-heatmap/master executed by <my personal website>` (as @Natenom suggested).

To the developers, The following is a diff with these changes that you can apply to make progress on this issue.

```
diff --git a/strava_local_heatmap.py b/strava_local_heatmap.py
index 84a4496..0765b36 100644
--- a/strava_local_heatmap.py
+++ b/strava_local_heatmap.py
@@ -36,11 +36,14 @@ HEATMAP_MARGIN_SIZE = 32 # margin around heatmap trackpoints in pixel
 
 PLT_COLORMAP = 'hot' # matplotlib color map
 
-OSM_TILE_SERVER = 'https://maps.wikimedia.org/osm-intl/{}/{}/{}.png' # OSM tile url from https://wiki.openstreetmap.org/wiki/Tile_servers
+OSM_TILE_SERVER = 'https://tile.openstreetmap.org/{}/{}/{}.png' # OSM tile url from https://wiki.openstreetmap.org/wiki/Tile_servers
 OSM_TILE_SIZE = 256 # OSM tile size in pixel
 OSM_MAX_ZOOM = 19 # OSM maximum zoom level
 OSM_MAX_TILE_COUNT = 100 # maximum number of tiles to download
 
+USER = '' # A way for the users running the program to identify themselves
+USER_AGENT = 'Strava-local-heatmap/master executed by %s' % USER
+
 # functions
 def deg2xy(lat_deg: float, lon_deg: float, zoom: int) -> tuple[float, float]:
     """Returns OSM coordinates (x,y) from (lat,lon) in degree"""
@@ -89,7 +92,7 @@ def gaussian_filter(image: np.ndarray, sigma: float) -> np.ndarray:
 def download_tile(tile_url: str, tile_file: str) -> bool:
     """Download tile from url to file, wait 0.1s and return True (False) if (not) successful"""
 
-    request = Request(tile_url, headers={'User-Agent':'Mozilla/5.0'})
+    request = Request(tile_url, headers={'User-Agent': USER_AGENT})
 
     try:
         with urlopen(request) as response:
```

**Comment by remisalmon** [comment]
Sorry for the lack of response, the wikimedia maps public API was indeed locked down: https://wikitech.wikimedia.org/wiki/Maps/External_usage
> maps.wikimedia.org tiles may only be used by Wikimedia wikis, and sites hosted by [Wikimedia Affiliates](https://meta.wikimedia.org/wiki/Wikimedia_Affiliates).

We can hack our way around it but I would rather not, and the openstreetmap public API still works. I have a fix stashed somewhere I am going to push.

 Thanks for all the suggestions, I agree we should follow openstreetmap's policies.

**Comment by remisalmon** [comment]
This should be fixed by https://github.com/remisalmon/Strava-local-heatmap/commit/4e2ae7a5d4b9e8c0bf3acf1114895403d8c9d1bc and https://github.com/remisalmon/Strava-local-heatmap/commit/2ed4dcee1d6608b4ab7c78a2ee3dc4a78632eebb.

The OSM tiles won't look as good but at least they work (for now). If anyone want to make a case to the wikimedia foundation that we should poke their map API go for it :)
